INSERT INTO final.fct_delivery (
    -- delivery_id is generated by UUID
    order_id,
    customer_id,
    order_status,
    order_purchase_date,
    order_purchase_time,
    order_approved_at_date,
    order_approved_at_time,
    order_delivered_carrier_date,
    order_delivered_carrier_time,
    order_delivered_customer_date,
    order_delivered_customer_time,
    order_estimated_delivery_date,
    order_estimated_delivery_time,
    shipping_limit_date,
    shipping_limit_time
)

SELECT 
	so.order_id,
	dc.customer_id,
    so.order_status,
    dd1.dim_date AS order_purchase_date,
    dt1.dim_time AS order_purchase_time,
    dd2.dim_date AS order_approved_at_date,
    dt2.dim_time AS order_approved_at_time,
    dd3.dim_date AS order_delivered_carrier_date,
    dt3.dim_time AS order_delivered_carrier_time,
    dd4.dim_date AS order_delivered_customer_date,
    dt4.dim_time AS order_delivered_customer_time,
    dd5.dim_date AS order_estimated_delivery_date,
    dt5.dim_time AS order_estimated_delivery_time,
    dd6.dim_date AS shipping_limit_date,
    dt6.dim_date AS shipping_limit_time
FROM 
	stg.orders so
JOIN
	final.dim_customer dc ON so.customer_id = dc.customer_nk
JOIN
    final.dim_date dd1 ON dd1.date_actual = DATE(so.order_purchase_timestamp)
JOIN
    final.dim_time dt1 ON dt1.time_actual::time = (so.order_purchase_timestamp)::time
JOIN
    final.dim_date dd2 ON dd2.date_actual = DATE(so.order_approved_at)
JOIN
    final.dim_time dt2 ON dt2.time_actual::time = (so.order_approved_at)::time
JOIN
    final.dim_date dd3 ON dd3.date_actual = DATE(so.order_delivered_carrier_date)
JOIN
    final.dim_time dt3 ON dt3.time_actual::time = (so.order_delivered_carrier_date)::time
JOIN
    final.dim_date dd4 ON dd4.date_actual = DATE(so.order_delivered_customer_date)
JOIN
    final.dim_time dt4 ON dt4.time_actual::time = (so.order_delivered_customer_date)::time
JOIN
    final.dim_date dd5 ON dd5.date_actual = DATE(so.order_estimated_delivery_date)
JOIN
    final.dim_time dt5 ON dt5.time_actual::time = (so.order_estimated_delivery_date)::time
JOIN
    final.dim_date dd6 ON dd6.date_actual = DATE(so.shipping_limit_date)
JOIN
    final.dim_time dt6 ON dt6.time_actual::time = (so.shipping_limit_date)::time

	

ON CONFLICT(order_id, customer_id, order_status) 
DO UPDATE SET
    order_purchase_date = EXCLUDED.order_purchase_date,
    order_purchase_time = EXCLUDED.order_purchase_time,
    order_approved_at_date = EXCLUDED.order_approved_at_date,
    order_approved_at_time = EXCLUDED.order_approved_at_time,
    order_delivered_carrier_date = EXCLUDED.order_delivered_carrier_date,
    order_delivered_carrier_time = EXCLUDED.order_delivered_carrier_time,
    order_delivered_customer_date = EXCLUDED.order_delivered_customer_date,
    order_delivered_customer_time = EXCLUDED.order_delivered_customer_time,
    order_estimated_delivery_date = EXCLUDED.order_estimated_delivery_date,
    order_estimated_delivery_time = EXCLUDED.order_estimated_delivery_time,
    shipping_limit_date = EXCLUDED.shipping_limit_date,
    shipping_limit_time = EXCLUDED.shipping_limit_time,
    updated_at = CASE WHEN 
                        final.fct_delivery.order_purchase_date <> EXCLUDED.order_purchase_date
                        OR final.fct_delivery.order_purchase_time <> EXCLUDED.order_purchase_time
                        OR final.fct_delivery.order_approved_at_date <> EXCLUDED.order_approved_at_date
                        OR final.fct_delivery.order_approved_at_time <> EXCLUDED.order_approved_at_time
                        OR final.fct_delivery.order_delivered_carrier_date <> EXCLUDED.order_delivered_carrier_date
                        OR final.fct_delivery.order_delivered_carrier_time <> EXCLUDED.order_delivered_carrier_time
                        OR final.fct_delivery.order_delivered_customer_date <> EXCLUDED.order_delivered_customer_date
                        OR final.fct_delivery.order_delivered_customer_time <> EXCLUDED.order_delivered_customer_time
                        OR final.fct_delivery.order_estimated_delivery_date <> EXCLUDED.order_estimated_delivery_date
                        OR final.fct_delivery.order_estimated_delivery_time <> EXCLUDED.order_estimated_delivery_time
                        OR final.fct_delivery.shipping_limit_date <> EXCLUDED.shipping_limit_date
                        OR final.fct_delivery.shipping_limit_time <> EXCLUDED.shipping_limit_time
                THEN 
                        CURRENT_TIMESTAMP
                ELSE
                        final.fct_delivery.updated_at
                END;