INSERT INTO final.fct_review (
    -- review_id is generated by UUID
    order_id,
    customer_id,,
    order_status,
    review_score,
    review_comment_title,
    review_comment_message,
    review_creation_date,,
    payment_value,,
    product_id,
    geolocation_zip_code_prefix
)

SELECT 
	so.order_id,
    dc.customer_id,,
    so.order_status,
    sor.review_score,
    sor.review_comment_title,
    sor.review_comment_message,
    dd1.review_creation_date,
    sop.payment_value,,
    dp.product_id,
    dg.geolocation_zip_code_prefix
FROM 
	stg.orders so
JOIN
	final.dim_customer dc ON so.customer_id = dc.customer_nk
JOIN
    stg.order_reviews sor ON sor.order_id = so.order_id
JOIN
    final.dim_time dd1 ON dd1.date_actual = sor.review_creation_date
JOIN
    stg.order_payments sop ON sop.order_id = so.order_id
JOIN
    final.dim_product dp ON dp.product_nk = so.product_id
JOIN
    final.dim_geolocation dg ON dg.geolocation_zip_code_prefix = dc.customer_zip_code_prefix

ON CONFLICT(order_id, customer_id, order_status, product_id) 
DO UPDATE SET
    review_score = EXCLUDED.review_score,
    review_comment_title = EXCLUDED.review_comment_title,
    review_comment_message = EXCLUDED.review_comment_message,
    review_creation_date = EXCLUDED.review_creation_date,
    payment_value = EXCLUDED.payment_value,
    product_id = EXCLUDED.product_id,
    geolocation_zip_code_prefix = EXCLUDED.geolocation_zip_code_prefix,
    updated_at = CASE WHEN 
                        final.fct_review.review_score <> EXCLUDED.review_score
                        OR final.fct_review.review_comment_title <> EXCLUDED.review_comment_title
                        OR final.fct_review.review_comment_message <> EXCLUDED.review_comment_message
                        OR final.fct_review.review_creation_date <> EXCLUDED.review_creation_date
                        OR final.fct_review.payment_value <> EXCLUDED.payment_value
                        OR final.fct_review.geolocation_zip_code_prefix <> EXCLUDED.geolocation_zip_code_prefix
                THEN 
                        CURRENT_TIMESTAMP
                ELSE
                        final.fct_review.updated_at
                END;