INSERT INTO final.fct_order_delivery (
    -- fct_order_id is generated by UUID
    order_id,
    customer_id,
    order_purchase_date,
    order_approved_at_date,
    order_delivered_carrier_date,
    order_delivered_customer_date,
    order_estimated_delivery_date,
    day_process,
    day_success
)

select 
    so.order_id::uuid,
    dc.customer_id,
    dd1.date_id AS order_purchase_date,
    dd2.date_id AS order_approved_at_date,
    dd3.date_id AS order_delivered_carrier_date,
    dd4.date_id AS order_delivered_customer_date,
    dd5.date_id AS order_estimated_delivery_date,
    
    -- Calculate day process using direct date subtraction
    (TO_DATE(dd3.date_id::text, 'YYYYMMDD') - TO_DATE(dd1.date_id::text, 'YYYYMMDD')) AS day_process,

    -- Calculate day success
    (TO_DATE(dd4.date_id::text, 'YYYYMMDD') - TO_DATE(dd1.date_id::text, 'YYYYMMDD')) AS day_success
	FROM 
	    stg.orders so
	JOIN
	    final.dim_customer dc ON so.customer_id = dc.customer_nk
	JOIN 
	    final.dim_date dd1 ON dd1.date_actual = TO_DATE(so.order_purchase_timestamp::text, 'YYYY-MM-DD')
	JOIN 
	    final.dim_date dd2 ON dd2.date_actual = TO_DATE(so.order_approved_at::text, 'YYYY-MM-DD')
	JOIN 
	    final.dim_date dd3 ON dd3.date_actual = TO_DATE(so.order_delivered_carrier_date::text, 'YYYY-MM-DD')
	JOIN 
	    final.dim_date dd4 ON dd4.date_actual = TO_DATE(so.order_delivered_customer_date::text, 'YYYY-MM-DD')
	JOIN 
	    final.dim_date dd5 ON dd5.date_actual = TO_DATE(so.order_estimated_delivery_date::text, 'YYYY-MM-DD')

ON CONFLICT(order_delivery_id, order_id, customer_id) 
DO UPDATE SET
    order_purchase_date = EXCLUDED.order_purchase_date,
    order_approved_at_date = EXCLUDED.order_approved_at_date,
    order_delivered_carrier_date = EXCLUDED.order_delivered_carrier_date,
    order_delivered_customer_date = EXCLUDED.order_delivered_customer_date,
    order_estimated_delivery_date = EXCLUDED.order_estimated_delivery_date,
    updated_at = CASE WHEN 
                        final.fct_order_delivery.order_purchase_date <> EXCLUDED.order_purchase_date
                        OR final.fct_order_delivery.order_approved_at_date <> EXCLUDED.order_approved_at_date
                        OR final.fct_order_delivery.order_delivered_carrier_date <> EXCLUDED.order_delivered_carrier_date
                        OR final.fct_order_delivery.order_delivered_customer_date <> EXCLUDED.order_delivered_customer_date
                        OR final.fct_order_delivery.order_estimated_delivery_date <> EXCLUDED.order_estimated_delivery_date
                THEN 
                        CURRENT_TIMESTAMP
                ELSE
                        final.fct_order_delivery.updated_at
                END;